### ISSUE TITLE
Remove Secret-Key

### ISSUE THREAD

**Issue by arunodhayamsam** [s3lva-kumar/terraform-eks-plugin#1]
Hi @s3lva-kumar, This is Arun 🧛. Your AWS EKS <img src="https://www.vectorlogo.zone/logos/terraformio/terraformio-icon.svg" alt="terraform" title="terraform" width="20" height="22"/> plan was helpful to create the perfect EKS cluster with really needed addons like EBS provisioner, metrics server. Thanks much for that.

There is small change that  you missed to hide the your credentials on this [file](https://github.com/s3lva-kumar/eks-plugin/blob/master/terraform-amazon-metrics-server/provider.tf). So please do necessary action to achieve the secure TF plan.

**Comment by s3lva-kumar** [comment]
Hello @arunodhayamsam 🧛, it's my bad. However it is temporary sandbox creds so it's expired. Although, I will remove it soon, thanks for letting me know.

**Comment by arunodhayamsam** [comment]
Ohh.. Okay @s3lva-kumar . I know that you are giving more importance to security 🤠

**Comment by s3lva-kumar** [comment]
Issue resolved
